using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class EnemyController : MonoBehaviour
{
    
    public float maxSpeed=2;
    public int damage=1;

    [HideInInspector]
    public SpriteRenderer sr;
    void Start()
    {
        sr=GetComponent<SpriteRenderer>();
    }

   
    public void Flip() 
    {
        sr.flipX=!sr.flipX;
    }
    void OnTriggerEnter2D(Collider2D other)
    {
   if(other.tag=="player")
    {
        FindObjectOfType<PlayerStats>().TakeDamage(damage);
        Flip();
    }
    else if(other.tag=="wall")
    {
 Flip();
    }

}
}